proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: wim
    password: maracuya
    groups: admins
  docker:
    internal-networking: true
  specs:
  - id: dashboard
    display-name: Maracuya Dashboard
    description: Application to administre hours and invoices
    container-cmd: ["R", "-e", "shiny::runApp('/root/app')"]
    container-image: maracuya/my_image
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
